### ISSUE TITLE
As PRODUCT OWNER, I want the Q3 2024 CDISC CT be available in CDISC Library.

### ISSUE THREAD

**Issue by chowsanthony** [cdisc-org/cdisc-library-standard-products-pipeline#129]

**Comment by chowsanthony** [comment]
Note: Please note the src-files repo has been moved to GitHub.

Acceptance criteria, for both API and DSB:
* The new TMF CT subset will be made available. New also will be an API path parameter for this subset.
* The /mdr/lastupdate endpoint returns the current date
* Changes to existing CT subsets will be accessible.

**Comment by lexjansen** [comment]
Do we have an Excel download template for this? Just like we created export.mrct.workbook.template.xlsx last time.

**Comment by lexjansen** [comment]
Why will there be a new API path parameter for this subset. It's another CT subset.
